[tool.poetry]
name = "io_scene_vrm"
version = "1.0.0" # Dummy version. See __init__.bl_info["version"] instead.
description = ""
authors = ["Isamu Mogi <isamu@leafytree.jp>", "iCyP"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.10.*"
bpy = "3.6.*"

[tool.poetry.group.dev.dependencies]
black = "*"
flake8 = "*"
flake8-bandit = "*"
flake8-bugbear = "*"
flake8-no-pep420 = "*"
flake8-scream = "*"
flake8-simplify = "*"
flake8-spellcheck = "*"
isort = "*"
mypy = "*"
pep8-naming = "*"
pylint = "*"
pyright = "*"

[tool.black]
target-version = ["py39"]

[tool.mypy]
python_version = "3.9"
strict = true
disallow_any_unimported = true
disallow_any_decorated = true
disallow_any_explicit = true
mypy_path = "$MYPY_CONFIG_FILE_DIR/typings"

[tool.pylint.main]
py-version = "3.9"

[tool.pylint.format]
max-line-length = 120 # https://wiki.blender.org/wiki/Process/Addons/Guidelines
max-module-lines = 3000

[tool.pylint.design]
max-args = 15
max-bool-expr = 14
max-branches = 121
max-locals = 99
max-attributes = 15
max-public-methods = 35
max-returns = 22
max-statements = 520
min-public-methods = 0

[tool.pylint.refactoring]
max-nested-blocks = 8

[tool.pylint."messages control"]
disable = [
    "broad-exception-caught",
    "duplicate-code", # https://github.com/PyCQA/pylint/issues/214
    "fixme",
    "import-error",
    "import-outside-toplevel",
    "invalid-name",
    "missing-class-docstring",
    "missing-function-docstring",
    "missing-module-docstring",
]

[tool.pyright]
pythonVersion = "3.9"
pythonPlatform = "All"
typeCheckingMode = "strict"

reportMissingModuleSource = false
reportUnknownArgumentType = false
reportUnknownMemberType = false
reportUnknownVariableType = false
reportImportCycles = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
